import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/navbar";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Social Media App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full px-4 bg-gray-300 md:px-8 lg:px-16 xl:px-31 2xl:px-64">
          <Navbar></Navbar>
        </div>

        <div className=" px-4 bg-gray-100 md:px-8 lg:px-16 xl:px-31 2xl:px-64">
        {children}
        </div>
      </body>
    </html>
    </ClerkProvider>
  );
}
